version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Map host port 3000 to container port 3000
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=Arun@mysql@1601
      - DB_NAME=app_db
      - DB_PORT=3306
    depends_on:
      - db
    networks:
      - app-network
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=Arun@mysql@1601
      - MYSQL_DATABASE=app_db
    ports:
      - "3308:3306" # Expose MySQL port (optional for external access)
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mysql-data: # Persistent storage for MySQL data

networks:
  app-network:
    driver: bridge